github:
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
  features:
    issues: true
notifications:
  jira_options: "link"
jenkins:
  github_whitelist:
    - "renovate-bot[bot]"
